fileFilter: "boshcli*.sh" 
#srcDirName: "/links/Stefan/privat/myPrg/MyPythonPrgs/ConvertDirectoryTree/testdata/src"
srcDirName: "/links/workdata/BlueMix/gits/GHE/doctor-service-ops/ssh"
#tgtDirName: "/home/zinks/Desktop"
tgtDirName: "/home/zinks/.ssh"
